FROM python:3.11.4

RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean

WORKDIR /chatops_udv/fast_api
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# CMD ["python3", "database/check_doc_table.py"]
# CMD ["python3", "main.py"]

CMD ["sh", "-c", "python3 script.py && python3 main.py"]