FROM python:3.11-slim

RUN pip install poetry==1.8.2

WORKDIR /chatops_udv/fast_api

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --no-root

COPY . .

RUN mkdir -p /chatops_udv/fast_api/certs
RUN apt-get update && apt-get install -y openssl
RUN openssl req -x509 -newkey rsa:4096 -nodes -out /chatops_udv/fast_api/certs/cert.pem -keyout /chatops_udv/fast_api/certs/key.pem -days 365 \
    -subj "/C=RU/ST=Moscow/L=Moscow/O=Organization/OU=Org/CN=localhost"

CMD ["sh", "-c", "poetry run python3 main.py"]