FROM python:3.11-slim

RUN pip install poetry==1.8.2

WORKDIR /chatops_udv/fast_api

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --no-root

COPY . .

CMD ["sh", "-c", "poetry run python3 main.py"]