"""change points to numeric

Revision ID: 27c0add16c87
Revises: ec5541b43455
Create Date: 2024-07-08 22:20:08.487846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c0add16c87'
down_revision: Union[str, None] = 'ec5541b43455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'points',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
