"""add chunk_size, embedding_model to doc

Revision ID: 452969261a3e
Revises: 27c0add16c87
Create Date: 2024-07-15 21:19:10.334491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452969261a3e'
down_revision: Union[str, None] = '27c0add16c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('doc', sa.Column('embedding_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'embedding_model')
    op.drop_column('doc', 'chunk_size')
    # ### end Alembic commands ###
