"""answer_question_system, test_system

Revision ID: 584d86fdd58e
Revises: c171c02ed299
Create Date: 2024-07-03 21:24:02.210650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584d86fdd58e'
down_revision: Union[str, None] = 'c171c02ed299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_question_system', sa.Column('question', sa.String(), nullable=False))
    op.add_column('answer_question_system', sa.Column('answer', sa.Boolean(), nullable=False))
    op.drop_column('answer_question_system', 'is_answered')
    op.drop_column('answer_question_system', 'rigth_answer')
    op.add_column('test_system', sa.Column('right_answer', sa.String(), nullable=False))
    op.drop_column('test_system', 'rigth_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_system', sa.Column('rigth_answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('test_system', 'right_answer')
    op.add_column('answer_question_system', sa.Column('rigth_answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer_question_system', sa.Column('is_answered', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('answer_question_system', 'answer')
    op.drop_column('answer_question_system', 'question')
    # ### end Alembic commands ###
