"""add embedding tokens

Revision ID: 7274eeb44a12
Revises: 36eb069e19da
Create Date: 2024-07-25 10:57:26.589875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7274eeb44a12'
down_revision: Union[str, None] = '36eb069e19da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_statistic', sa.Column('embedding_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_statistic', 'embedding_tokens')
    # ### end Alembic commands ###
