"""remove path from doc and add viewed to feedback

Revision ID: 82b44b92271e
Revises: adb904199354
Create Date: 2024-04-09 22:01:21.654513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b44b92271e'
down_revision: Union[str, None] = 'adb904199354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'path')
    op.add_column('feedback', sa.Column('viewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'viewed')
    op.add_column('doc', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###