"""for_semantic_cache

Revision ID: 870dc195798d
Revises: a4e3cbde5f92
Create Date: 2024-10-09 06:37:15.938728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '870dc195798d'
down_revision: Union[str, None] = 'a4e3cbde5f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer_question_system', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('request_statistic', sa.Column('from_cache', sa.Boolean(), nullable=True))
    op.alter_column('request_statistic', 'prompt_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_statistic', 'prompt_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('request_statistic', 'from_cache')
    op.alter_column('answer_question_system', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
