"""remove company_representative, add gigachat_time

Revision ID: adb904199354
Revises: 703491095928
Create Date: 2024-04-06 20:43:56.983728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb904199354'
down_revision: Union[str, None] = '703491095928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_statistic', sa.Column('gigachat_time', sa.Numeric(precision=10, scale=3), nullable=True))
    op.alter_column('request_statistic', 'lead_time', new_column_name='total_time')
    op.drop_column('user', 'company_representative')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_representative', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('request_statistic', 'gigachat_time')
    op.alter_column('request_statistic', 'total_time', new_column_name='lead_time')
    # ### end Alembic commands ###